-- [Char] === list of character
-- Int === Integer with a minnimum and a maximum value 2147483647 and -2147483647
-- Integer === Integer without limits 
-- Float === Number with "," 25.132742
-- Double === Float with double precision 25.132741228718345
-- LIsts === Array
-- Tuples === () instead of [] Every value will have his own type 
-- ++ === Adding two list together
-- concat === combine all element of a list
-- head return the first item ( "Hello") return h 
-- tail return the string or list without the first value ("Hello") return ello
-- init return first item of a list
-- last return last item of a list
-- == Check for Equality
-- /= Check for ineguality
-- > Greater than
-- < Lower than
-- >= Greather or egual to
-- <= Lower or equal to 
-- :info give the priority, but it's often better to use